### ISSUE TITLE
provider error

### ISSUE THREAD

**Issue by Perfect-Web** [xphere/one-time-access-bundle#1]
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Provider must implement Berny\OneTimeAccessBundle\Security\ProviderInterface interface.' in l/vendor/berny/one-time-access-bundle/Berny/OneTimeAccessBundle/Security/Authentication/Provider/Provider.php on line 30 when the provider is a doctrine repository, and this is on symfony 2.3

**Comment by Perfect-Web** [comment]
it works fine if i use as ota service, but not for repository

**Comment by xphere** [comment]
Thanks, can you provide more insight about your project? A simple failing example will do.

**Comment by LubosK** [comment]
Hi xphere,
I updated my project with composer update and then if I want cache:clear I get this error message:
[Symfony\Component\DependencyInjection\Exception\RuntimeException]
  The parent definition "xphere.ota.provider" defined for definition "security.authentication.provider.one_time_access.main" does not exist.

**Comment by xphere** [comment]
Hi @LubosK, your issue seem unrelated to the one discussed here. Can you please open a new one, please? Would be glad to help.

@Perfect-Web: is your issue fixed?

**Comment by xphere** [comment]
Closed due to inactivity
