### ISSUE TITLE
xphere.ota.provider

### ISSUE THREAD

**Issue by LubosK** [xphere/one-time-access-bundle#2]
Hi xphere, 

I updated my project via composer update and then if I want cache:clear I get this error message: 

[Symfony\Component\DependencyInjection\Exception\RuntimeException]
  The parent definition "xphere.ota.provider" defined for definition "security.authentication.provider.one_time_access.main" does not exist.

**Comment by xphere** [comment]
Sorry, I messed up things when moving between namespaces, will fix in a minute and tag as `1.1`.
Please do require your dependency to be `>=1.1` or `^1.1` and try again `composer install`.

**Comment by LubosK** [comment]
Thanks, it seems to be okay.
